### ISSUE TITLE
Compatibility with `Composer\InstalledVersions` API

### ISSUE THREAD

**Issue by someniatko** [bamarni/composer-bin-plugin#138]
Currently if you run a binary from a "bin", and it uses [Composer's `InstalledVersions` API](https://getcomposer.org/doc/07-runtime.md#installed-versions), it will report packages from the main project's directory `composer.json`, instead of bin's.

This behavior breaks, for example, `roave/infection-static-analysis-plugin`, which [relies on such checks](https://github.com/Roave/infection-static-analysis-plugin/blob/1.22.x/bin/roave-infection-static-analysis-plugin#L55) (which are wrapped in `ocramius/package-versions` lib, see [here](https://github.com/Ocramius/PackageVersions/blob/2.6.x/src/PackageVersions/Versions.php#L36)).

I'm not sure this plugin itself can do something about it -- maybe it requires changes to the Composer plugin system itself, but it is a problem nevertheless.

Also see https://github.com/Ocramius/PackageVersions/issues/220

**Comment by theofidry** [comment]
>it will report packages from the main project's directory composer.json, instead of bin's.

Isn't it a problem of the binary tool picking up the wrong `composer.json` or autoload file? (in which case often you can reconfigure them)

**Comment by someniatko** [comment]
The binary tool in question does not "pick up" the `composer.json` on its own, it just uses (through a library, but nevertheless) the API Composer provides. IMO there should be a way for the bin plugin to report to the Composer itself which `composer.json` is the correct one, so Composer's InstalledVersions API reports packages correctly.

**Comment by theofidry** [comment]
>IMO there should be a way for the bin plugin to report to the Composer itself which composer.json is the correct one, so Composer's InstalledVersions API reports packages correctly.

- how would you do that though?
- how do you define what is the "correct composer.json": what if a bin tool is relying of the `InstalledVersions` from the bin directory not the root one?

From a brief glance, it looks like `Versions::*` is relying on the vendor dirs registered to the class loaders, which hints its likely related to what autoloader is autoloaded. #141 seems to confirm this.

To be clear: I do not mean there is nothing more to do here, but I don't think I understand the problem neither.

**Comment by someniatko** [comment]
Yes, you are right! See https://github.com/bamarni/composer-bin-plugin/pull/141#discussion_r980394614
