### ISSUE TITLE
Inherit from github-oauth main composer.json

### ISSUE THREAD

**Issue by oleg-andreyev** [bamarni/composer-bin-plugin#150]
It would be great if we have inherit config-partially from main composer.json

Example: `github-oauth`

**Comment by theofidry** [comment]
I really like the idea and totally see the need for it, but I unfortunately think it's completely out of scope of this project. This project is purely executing the original command in another directory. Doing anything beyond really requires a complete shift and a lot more tinkering.

However, maybe it is a case where https://github.com/wikimedia/composer-merge-plugin may help and if you find a solution with it I would be more than happy to have a doc entry for it.

**Comment by theofidry** [comment]
Closing for the reason mentioned above.

I do see the appeal and use case, but this introduce a really complex set of problem which the merge plugin aims to tackle and that is unfortunately really not simple.
