### ISSUE TITLE
Composer with options is not applied when `forward-command` option is turn on

### ISSUE THREAD

**Issue by llaville** [bamarni/composer-bin-plugin#158]
When you try to see what dependencies will be update with following command, (and `forward-command` option enabled) : 

```shell
composer update --dry-run --prefer-dist --no-dev
```

Then dependencies specified into `vendor-bin` are updated 

When `forward-command` option is disabled, the dry-run option is in effect and no vendor-bin deps are updated

**Comment by llaville** [comment]
It's same for all options: 

If I declare all vendor-bin dependencies to install with such format (NB the `require-dev` setting) :  

```json
{
    "require-dev": {
        "vendor/package": "constraint"
    }
}
```

When `forward-command` option is enabled, the `composer update --no-dev` still continue to update vendor-bin declared as previous.

**Comment by theofidry** [comment]
thanks for the report I'll check that today

**Comment by theofidry** [comment]
@llaville could you try to provide the output with `-vvv`? I somehow can't reproduce it:

```
$ composer update --dry-run -vvv 2>&1 | grep 'bamarni-bin'
[bamarni-bin] Calling onCommandEvent().
[bamarni-bin] The command is being forwarded.
[bamarni-bin] Original input: update --dry-run -vvv.
[bamarni-bin] Current working directory: /path/to/project
[bamarni-bin] Checking namespace vendor-bin/phpstan
[bamarni-bin] Changed current directory to vendor-bin/phpstan.
[bamarni-bin] Running `@composer update --dry-run -vvv --working-dir='.'`.
[bamarni-bin] Changed current directory to /path/to/project.
```

As you can see in the above, the command executed was `@composer update --dry-run -vvv --working-dir='.'` (and I didn't get an update).

**Comment by llaville** [comment]
@theofidry Sorry, I've lost context. 
Working recently on many projects at same time, I don't remember what project was on origin !
So I'll close this issue (my bad ;-)

BTW, I've noticed a strange behaviour with `outdated` command (forwarded). I'll open a new report with all details this time ;-)

**Comment by llaville** [comment]
@theofidry Already referenced by issue https://github.com/bamarni/composer-bin-plugin/issues/149
