### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by theofidry** [bamarni/composer-bin-plugin#21]
Maybe a bit of branding at some point could make the project a bit more attractive, dunno :)

I've come across https://github.com/lerna/lerna, it's very similar, might be worth trying to mention them at some point to show that this approach is not unique to PHP/Composer.

**Comment by bamarni** [comment]
I couldn't come up with a better name, feel free to suggest 😸 

FYI there are still pending discussions in composer about this topic (eg. https://github.com/composer/composer/issues/5390), so maybe this will be tackled in composer itself at some point.

**Comment by ScreamingDev** [comment]
Use the current discussion in composer and make them take it as "composer/tools" ;-)
Perhaps also solving the "require-tools" issue there.

https://github.com/composer/composer/issues/9636
