### ISSUE TITLE
Allow defining the bin dependencies in the main `package.json`

### ISSUE THREAD

**Issue by jtojnar** [bamarni/composer-bin-plugin#28]
If all developer wants is to install one bin dependency per namespace, creating the separate `package.json` file for each of them feels like an overkill.

How do you feel about adding the following sugar?

```json
{
    "extra": {
        "bamarni-bin": {
            "packages": {
                "cs": {
                    "friendsofphp/php-cs-fixer": "^2.3"
                },
                "lint": {
                    "jakub-onderka/php-parallel-lint": "^0.9.2"
                },
                "phpstan": {
                    "phpstan/phpstan": "^0.7.0",
                    "phpstan/phpstan-nette": "^0.7.0"
                }
            }
        }
    }
}
```

**Comment by bamarni** [comment]
The current implementation implies that the plugin doesn't know anything about dependencies, it's basically just a helper proxy command that'll run in a sub composer project, similar to "composer global".

As such, there is unfortunately no way to have this kind of sugar without making drastic refactoring. And I'd like to keep the plugin simple.
