### ISSUE TITLE
Document that users should force composer to create composer.json file when using a new vendor-bin namespace

### ISSUE THREAD

**Issue by Ayesh** [bamarni/composer-bin-plugin#30]
Hi Bilal,
Thanks for this awesome plugin. I use it in all my computers and helped immensely to organize my global composer packages. 

When we run `composer bin example`, composer changes the directory to `vendor-bin/example`, and executes the command specified next. Composer 1.5.1 came with a new feature that it checks scans the directories upwards until it finds a `composer.json` file if the current directory does not contain a `composer.json` file. 

User is prompted of course, and the default value is set so that composer is allowed to use the root level `composer.json` file. Can we update the `README.txt` of this project to indicate that users wishing to install something in a new vendor-bin namespace should answer No?

Thanks.

**Comment by Ayesh** [comment]
![cc](https://user-images.githubusercontent.com/811553/30005912-73862098-910a-11e7-82b7-26e2b59f7fb9.png)

**Comment by theofidry** [comment]
I'm 👍 for the message. @Ayesh do you mind opening a PR for it?

It would be cool however if we could completely disable that question as in the case of that plugin, it makes no sense at all.

**Comment by Ayesh** [comment]
@theofidry thanks!
I don't really know much about the Composer inner APIs, but there is an option (`-d` / `--working-dir=`)to explicitly set the working directory to whatever directory we want. Perhaps this plugin can enforce this... I will see what I can pull off.

**Comment by bamarni** [comment]
Thanks, the fix LGTM. Hopefully your PR upstream gets accepted.

**Comment by Ayesh** [comment]
Composer PR was just accepted!
