### ISSUE TITLE
Bin directory

### ISSUE THREAD

**Issue by theofidry** [bamarni/composer-bin-plugin#4]
In my `composer.json` I have:

```json
"config": {
        "bin-dir": "bin",
        "sort-packages": true
    }
```

In my other projects with the same config, I properly have my executables under `bin` instead of the default `vendor/bin`. However this plugin does not seem to take that into account and put executables in `vendor/bin` still.

**Comment by bamarni** [comment]
Local config was indeed ignored, should be better now!
