### ISSUE TITLE
[Composer][Packagist] Composer packages aren't in sync

### ISSUE THREAD

**Issue by rvitaliy** [bamarni/composer-bin-plugin#46]
global `composer.json`:
```
$ cat  ~/.composer/composer.json 
{
    "require": {
        "bamarni/composer-bin-plugin": "^1.2"
    }
}
```
current installed version:
```
$ composer global show  | grep bamarni
Changed current directory to ~/.composer
bamarni/composer-bin-plugin         v1.2.0
```
try to update:
```
$ composer global update
Changed current directory to ~/.composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

github current version `1.3`: https://github.com/bamarni/composer-bin-plugin/releases
packagist current version `1.2`: https://packagist.org/packages/bamarni/composer-bin-plugin

**Comment by theofidry** [comment]
Hm looks like I didn't update my packages to the new Packagist hook, will try to look into it ASAP

**Comment by theofidry** [comment]
@bamarni would it be possible to have writes for this package on Packagist as well? Alternatively you can update it yourself

**Comment by bamarni** [comment]
It seems up-to-date now, @theofidry I've added you on packagist as well
