### ISSUE TITLE
Need to update the scopes composer.json when installing humbug/php-scoper per docs

### ISSUE THREAD

**Issue by JoshMoreno** [bamarni/composer-bin-plugin#49]
When following the [docs](https://github.com/humbug/php-scoper#composer) to install locally rather than globally it says to do:

```bash
composer require --dev bamarni/composer-bin-plugin
composer bin php-scoper require --dev humbug/php-scoper
```

but since `humbug/php-scoper` has a `dev-master` requirement the scopes `composer.json` needs to be updated or it will error out on the second command. The below will is what it should be.

```bash
composer require --dev bamarni/composer-bin-plugin
composer bin php-scoper config minimum-stability dev
composer bin php-scoper config prefer-stable true 
composer bin php-scoper require --dev humbug/php-scoper
```

**Comment by theofidry** [comment]
Hm Indeed, would you mind opening a PR fixing it?
