### ISSUE TITLE
Create autoloader that include all package namespaces

### ISSUE THREAD

**Issue by ScreamingDev** [bamarni/composer-bin-plugin#57]
Right now every package namespace creates its own autoloader:

* vendor/autoload.php
* vendor-bin/foo/vendor/autoload.php
* vendor-bin/bar/vendor/autoload.php
* vendor-bin/baz/vendor/autoload.php

From my own experience and lately discussed in https://github.com/composer/composer/issues/9636
a custom autoloader could be a thing:

* The vendor/autoload.php should append all the swapped autoloader too
* The swapped autoloader should append the application autoloader

Right now developer can do this on their own:

```php
<?php

require_once 'vendor-bin/test/vendor/autoload.php';
require_once 'vendor/autoload.php';
```

But this needs some hands on when adding another section

```bash
composer bin require new-section bar/baz
```

Having this more dynamically would be a little helper.

## Suggestion

The common/central "vendor/autoload.php" should be changed to:

```php
require_once 'vendor/composer/autoload_real.php';

$loader = ComposerAutoloaderInit1234::getLoader();

require_once 'vendor-bin/tools/dev/autoload.php';
require_once 'vendor-bin/tools/tool-a/autoload.php';
require_once 'vendor-bin/tools/tool-b/autoload.php';

return $loader;
```

In the same order as given in the JSON, to give users control about the autoloading order.
While the single tools put their own autoloader on top ("vendor-bin/tools/dev/autoload.php"):

```php
require_once '/vendor/tools/composer/autoload_real.php';

$loader = ComposerAutoloaderInit6789::getLoader();

require_once 'vendor/autoload.php';

return $loader;
```

Something like this (just a quick fuzzy example).

Note: Including each another file does not lead to endless recursive includes.
The `require_once` returns the object on the first include and just `TRUE` for any further call.

**Comment by theofidry** [comment]
I think combining the autoloaders of multiple vendor-bin is a terrible idea: it completely defeat the purpose of Composer which is to prevent you to autoload incompatible code and will lead to subtle and terribly hard to debug issues that can pop up at any time

**Comment by theofidry** [comment]
Closing for the reasons explained in #58
