### ISSUE TITLE
Composer plugin support in namespaces?

### ISSUE THREAD

**Issue by AndreasA** [bamarni/composer-bin-plugin#62]
Is there a way to add support for composer plugins that are defined in namespaces? e.g. something like `composer bin namespace-foo plugin-bar options`? 

I guess one solution would be to add the namespaced version as plugin to the root composer.json?

I am especially talking about plugins that provide composer commands

**Comment by theofidry** [comment]
Shouldn't that already work? If it doesn't it may be because the plugin-bar detects its being used within the command and tries to kick in before the barmani one in which case I have no idea how this could be fixed

**Comment by AndreasA** [comment]
If I use the following setup:

- `vendor-bin/composer-unused/composer.json`:
```json
{
    "require": {
        "php": "^8.1",
        "composer-runtime-api": "^2.2",
        "icanhazstring/composer-unused": "~0.7.12"
    },
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "icanhazstring/composer-unused": true
        }
    }
}
  ```
- `composer.json`:
```json
{
    "description": "Foo bar",
    "license": "MIT",
    "name": "foo/bar",
    "type": "project",
    "config": {
        "allow-plugins": {
            "bamarni/composer-bin-plugin": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": "^8.1",
        "composer-runtime-api": "^2.2",
        "bamarni/composer-bin-plugin": "^1.4"
    }
}
  ```

Then I install the composer dependencies for root and namespace:

```
composer install -o
composer bin composer-unused install -o
```

Then if I try to run the plugin:
```
 composer bin composer-unused unused
```

I get the error:

```
composer bin composer-unused unused


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "unused" is not defined.
```

If I do
```
cd vendor-bin/composer-unused
composer unused
```

it works but it is then using the wrong composer.json to validate against.

As the plugin provides a separate command too and switches to that anyway instead of the plugin, it isn't really that problematic in this scenario but it isn't working as it should.

I also tried to add `"icanhazstring/composer-unused": true` to the root composer.json but that doesn't work either.

**Comment by theofidry** [comment]
When you do:

```
 composer bin composer-unused unused
```

Shouldn't it work only if you install the plugin, not the package itself?

**Comment by AndreasA** [comment]
@theofidry the package is the plugin in v0.7: https://github.com/composer-unused/composer-unused/blob/0.7.12/composer.json#L3

**Comment by theofidry** [comment]
I see, then I'm not sure if it's an issue within Composer (rather more a question of how it deals with plugins) or the plugin itself that does not kick in at the right time. It needs further investigation

**Comment by AndreasA** [comment]
As mentiomed I am using the binary instead of the plugin anyway (also default implemrntation with 0.8-RC) but I noticed that it wasn't working as plugin, so I thought I would report it, but if there is no easy solution to this, it is find as it is too and can just be a known limitation.
