### ISSUE TITLE
Dev-Dependencies installed when using --no-dev option

### ISSUE THREAD

**Issue by ScreamingDev** [bamarni/composer-bin-plugin#65]
Composer-Bin-Plugin helps lowering the chance of version conflicts by separating tools into different directories.
Unfortunately none of these tools or "sub-composer" setups respect the options made on the top-level.
The composer-bin-plugin should forward some of the important or useful options (e.g. --no-dev).

Example of an "vendor-bin/foo/composer.json":

```json
{
  "autoload-dev": { "... stuff here ..." }
  "require-dev": {
    "only-for-deveolpment-here/some-package": "~1"
  }
}
```

Running `composer install --no-dev` (with lockfiles) present would ignore the "no-dev Option" and install the dev package. It also adds an autoloader that is never used in production mode. Forwarding the "no-dev Option" would solve this already.

**Comment by theofidry** [comment]
Checked in #106: it did work (before my changes) so if you still encounter the issue do open a new issue for it.
